/**
 * Human labels for API SSE `stage` codes.
 * Keep in sync with `draftlens_api.engine.status_stage_order.STAGE_RANK` keys on the API.
 */

export const PIPELINE_STAGE_LABELS: Record<string, string> = {
  UPLOAD_RECEIVED: "Upload received",
  APPLY_FIXES_STARTED: "Apply fixes from review",
  APPLY_FIXES_HYDRATE_STARTED: "Loading review for correction",
  APPLY_FIXES_HYDRATE_COMPLETE: "Review ledger loaded",
  FIX_JOB_CREATED_FROM_REVIEW: "Fix job linked to review",
  TRI_REVIEW_PANEL_STARTED: "Tri‑model review (parallel)",
  TRI_REVIEW_PANEL_COMPLETE: "Tri‑model review complete",
  SUPPORTING_FILES_INGESTED: "Supporting files ingested",
  EVIDENCE_PARSE_STARTED: "Evidence parse started",
  DOC_PARSED: "Document parsed",
  EVIDENCE_PARSED: "Evidence parsed",
  EVIDENCE_RETRIEVAL_READY: "Evidence retrieval ready",
  DOC_NORMALIZED: "Text normalized",
  CHUNKING_COMPLETE: "Chunking complete",
  MODEL_REVIEW_CLAUDE_STARTED: "Claude review",
  MODEL_REVIEW_CLAUDE_COMPLETE: "Claude review done",
  MODEL_REVIEW_CLAUDE_FAILED: "Claude review failed",
  MODEL_REVIEW_GPT_STARTED: "GPT review",
  MODEL_REVIEW_GPT_COMPLETE: "GPT review done",
  MODEL_REVIEW_GPT_FAILED: "GPT review failed",
  MODEL_REVIEW_GEMINI_STARTED: "Gemini review",
  MODEL_REVIEW_GEMINI_COMPLETE: "Gemini review done",
  MODEL_REVIEW_GEMINI_FAILED: "Gemini review failed",
  CROSS_MODEL_DEBATE_STARTED: "Conflicts flagged",
  CROSS_MODEL_DEBATE_ROUND_COMPLETE: "Debate round",
  ARBITER_SKIPPED_NO_QUORUM: "Arbitration skipped (no quorum)",
  ARBITER_SKIPPED_NO_CONFLICTS: "Arbitration skipped (no conflicts)",
  ARBITER_STARTED: "Arbiter",
  ARBITER_COMPLETE: "Arbiter complete",
  ITERATIVE_CYCLE_STARTED: "Convergence cycle",
  ITERATIVE_CYCLE_COMPLETE: "Convergence cycle done",
  ITERATIVE_SKIPPED_NO_QUORUM: "Convergence skipped (no quorum)",
  FIX_REAPPLY_STARTED: "Re-applying fixes",
  FIX_REAPPLY_COMPLETE: "Re-apply fixes done",
  FIX_BASELINE_REVIEW_STARTED: "Fix Mode baseline review",
  FIX_BASELINE_REVIEW_COMPLETE: "Fix Mode baseline review done",
  FIX_RECONCILIATION_CYCLE_STARTED: "Fix reconciliation cycle",
  FIX_RECONCILIATION_CYCLE_COMPLETE: "Fix reconciliation cycle done",
  FIX_CANDIDATE_GENERATION_STARTED: "Corrected candidate generation",
  FIX_CANDIDATE_GENERATION_COMPLETE: "Corrected candidate ready",
  FIX_CANDIDATE_TRI_REVIEW_STARTED: "Tri-review of corrected candidate",
  FIX_CANDIDATE_TRI_REVIEW_COMPLETE: "Tri-review of corrected candidate done",
  FINAL_ALIGNMENT_AUDIT_STARTED: "Final alignment audit",
  FINAL_ALIGNMENT_AUDIT_COMPLETE: "Final alignment audit passed",
  FINAL_ALIGNMENT_AUDIT_FAILED: "Final alignment audit failed",
  FIX_CONVERGENCE_REACHED: "Fix Mode convergence reached",
  FIX_HUMAN_FOLLOW_UP_REQUIRED: "Fix Mode human follow-up required",
  PARTIAL_CONSENSUS: "Partial consensus",
  HUMAN_FOLLOW_UP_REQUIRED: "Human follow-up required",
  CONVERGENCE_REACHED: "Convergence reached",
  PARTIAL_REVIEW_COMPLETE: "Partial review complete",
  PDF_RENDER_STARTED: "PDF rendering",
  PDF_RENDER_COMPLETE: "PDF rendering done",
  RENDERING_REVIEW_DOC: "Rendering review output",
  RENDERING_FIXED_DOC: "Rendering fix output",
  EXPORT_COMPLETE: "Export packaged",
  JOB_FAILED: "Job failed",
  FAIL_NO_REVIEWER_OUTPUT: "No valid reviewer output",
  SSE_PARSE_ERROR: "Event parse error",
  completed: "Complete",
  failed: "Failed",
};

export function stageLabel(stage: string): string {
  return PIPELINE_STAGE_LABELS[stage] ?? stage.replace(/_/g, " ");
}
